package com.pic.optimize.test.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pic.optimize.test.bean.QuestionInfo;
import com.pic.optimize.CardBean;

import com.pic.optimize.test.bean.QuestionInfoDao;
import com.pic.optimize.CardBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionInfoDaoConfig;
    private final DaoConfig cardBeanDaoConfig;

    private final QuestionInfoDao questionInfoDao;
    private final CardBeanDao cardBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionInfoDaoConfig = daoConfigMap.get(QuestionInfoDao.class).clone();
        questionInfoDaoConfig.initIdentityScope(type);

        cardBeanDaoConfig = daoConfigMap.get(CardBeanDao.class).clone();
        cardBeanDaoConfig.initIdentityScope(type);

        questionInfoDao = new QuestionInfoDao(questionInfoDaoConfig, this);
        cardBeanDao = new CardBeanDao(cardBeanDaoConfig, this);

        registerDao(QuestionInfo.class, questionInfoDao);
        registerDao(CardBean.class, cardBeanDao);
    }
    
    public void clear() {
        questionInfoDaoConfig.clearIdentityScope();
        cardBeanDaoConfig.clearIdentityScope();
    }

    public QuestionInfoDao getQuestionInfoDao() {
        return questionInfoDao;
    }

    public CardBeanDao getCardBeanDao() {
        return cardBeanDao;
    }

}
